/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;

import clases.camposOrigen;
import clases.conexionOrigen;
import java.awt.Image;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/**
 *
 * @author marqu
 */
public class selConexionOrigen extends javax.swing.JFrame {

    /**
     * Creates new form seleccionCon
     */
    public selConexionOrigen() {
        initComponents();
        
        tfxUsuario.setEnabled(false);
        txfContra.setEnabled(false);
        txfHost.setEnabled(false);
        jButtonConectar.setEnabled(false);
        
        
        
        
        
        Image icon = new ImageIcon(getClass().getResource("/iconos/con2.png")).getImage();
        setIconImage(icon);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        tfxUsuario = new javax.swing.JTextField();
        txfHost = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txfContra = new javax.swing.JPasswordField();
        jButtonConectar = new javax.swing.JButton();
        cmbSelector = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        lblStatus = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Migrador");
        setIconImages(null);
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Seleccion de Conexión ORIGEN"));

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setText("Nombre de Host:");

        jLabel2.setText("Usuario:");

        jLabel3.setText("Contraseña:");

        jButtonConectar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/connection.png"))); // NOI18N
        jButtonConectar.setText("Conectar:");
        jButtonConectar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConectarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(24, 24, 24))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(49, 49, 49)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButtonConectar, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 125, Short.MAX_VALUE))
                    .addComponent(txfHost)
                    .addComponent(tfxUsuario)
                    .addComponent(txfContra, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txfHost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfxUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(txfContra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(jButtonConectar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );

        cmbSelector.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "...", "SQL", "MYSQL" }));
        cmbSelector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbSelectorActionPerformed(evt);
            }
        });

        jLabel4.setText("Estado de la conexión:");

        lblStatus.setText(" ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblStatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbSelector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 16, Short.MAX_VALUE)))
                .addGap(28, 28, 28))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(cmbSelector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblStatus))
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void activar()
    {
        tfxUsuario.setEnabled(true);
        txfContra.setEnabled(true);
        txfHost.setEnabled(true);
        jButtonConectar.setEnabled(true);
    }
    
    private void desactivar(){
        
        tfxUsuario.setEnabled(false);
        txfContra.setEnabled(false);
        txfHost.setEnabled(false);
        jButtonConectar.setEnabled(false);

    }
    
    private void limpiar(){
    
         tfxUsuario.setText(null);
         txfContra.setText(null);
         txfHost.setText(null);
                 
    }
    
    private void conectar() throws SQLException
    {
        String seleccion = cmbSelector.getSelectedItem().toString();
        String host = txfHost.getText();
        String usuario = tfxUsuario.getText();
        String pass = txfContra.getText();
        
        
        
        
//        camposOrigen campo = new camposOrigen();
//        
//        campo.setHostname(host);
//        campo.setPassword(pass);
//        campo.setUsername(usuario);


        // Se guardan variables de txt en clase conexionOrigen
        conexionOrigen conexionO = new conexionOrigen();
        conexionO.setHostname(host);
        conexionO.setUsername(usuario);
        conexionO.setPassword(pass);
         
        
        if(txfHost.getText().length() == 0 || tfxUsuario.getText().length()==0 
                || txfContra.getText().length()==0)
        {
             JOptionPane.showMessageDialog(null, "No puede haber campos vacios", "Error", JOptionPane.ERROR_MESSAGE);
        }
        
        else
        {
            conexionOrigen cc = new conexionOrigen(host,usuario,pass);
            
            if(seleccion.equals("SQL"))
            {
                cc.sql(host);
                Connection cn = conexionOrigen.getConexion();
                if(cn == null)
                {
                    JOptionPane.showMessageDialog(null, "No hay conexion con el servidor SQL", "Error", JOptionPane.ERROR_MESSAGE);
                    lblStatus.setText("ERROR, no hay conexión");
                }
                else{
                
                    JOptionPane.showMessageDialog(null, "Conectado a SQL.");
                    lblStatus.setText("CONECTADO A SQL");
                    //jbSiguiente.setEnabled(true);
                    //Agregar ventana destino a SQL 
                    
                    this.setVisible(false);
//                    selConexionDestino conDestino = new selConexionDestino();
//                    conDestino.setVisible(true);
                      frameControlSQL sql = new frameControlSQL();
                      sql.setVisible(true);
                    

                }  
            }
            
            if(seleccion.equals("MYSQL"))
            {
                cc.mysql(host);
                Connection cn = conexionOrigen.getConexion();
                if(cn == null)
                {
                    JOptionPane.showMessageDialog(null, "No hay conexion con el servidor MYSQL", "Error", JOptionPane.ERROR_MESSAGE);
                    lblStatus.setText("ERROR, no hay conexión");
                }
                else{
                
                    JOptionPane.showMessageDialog(null, "Conectado a MYSQL.");
                    lblStatus.setText("CONECTADO A MYSQL");
                    
                    this.setVisible(false);
                    
                    selConexionDestino conDestino = new selConexionDestino();
                    conDestino.setVisible(true);
                     
                     
                }
                
            }
         
        }
    }
    
    private void jButtonConectarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConectarActionPerformed
        try {
            // TODO add your handling code here:
            conectar();
        } catch (SQLException ex) {
            Logger.getLogger(selConexionOrigen.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonConectarActionPerformed

    private void cmbSelectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbSelectorActionPerformed
        // TODO add your handling code here:
        String seleccion = cmbSelector.getSelectedItem().toString();
        
        if(seleccion.equals("..."))
        {
             jButtonConectar.setEnabled(false);
            limpiar();
            desactivar();
   
        }
        
        if(seleccion.equalsIgnoreCase("SQL"))
        {
            limpiar();
            jButtonConectar.setEnabled(true);
            activar();
        }
        
        if(seleccion.equalsIgnoreCase("MYSQL"))
        {
            limpiar();
            jButtonConectar.setEnabled(true);
            activar();
        }
        
        
  
        
    }//GEN-LAST:event_cmbSelectorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
       
        //</editor-fold>
        try{
  
        JFrame.setDefaultLookAndFeelDecorated(true);
        JDialog.setDefaultLookAndFeelDecorated(true);
        //UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
        UIManager.setLookAndFeel("com.sun.java.swing.plaf.nimbus.NimbusLookAndFeel");
        
        }
        catch (Exception e)
        {
        e.printStackTrace();
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new selConexionOrigen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbSelector;
    private javax.swing.JButton jButtonConectar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JTextField tfxUsuario;
    private javax.swing.JPasswordField txfContra;
    private javax.swing.JTextField txfHost;
    // End of variables declaration//GEN-END:variables
}
